if ( GetLocale() == "zhCN") then

	EUF_TEXT_TITLE = "界面增强"
	EUF_TEXT_OPTION = "界面增强设置选项"
	EUF_TEXT_HEADER = "Enhanced Unit Frames 参数设定"
	EUF_TEXT_DEFAULT = "默认设置"
	EUF_TEXT_CONFIRM = "确定"

	EUF_TEXT_OPTION_PLAYERELITE = "玩家显示精英头像"
	EUF_TEXT_OPTION_TOPPANEL = "调整头像位置适应顶部状态条"
	EUF_TEXT_OPTION_NOEXTBORDER = "不显示玩家头像扩展边框"
	EUF_TEXT_OPTION_PLAYERHPMP = "显示玩家的HP和MP"
	EUF_TEXT_OPTION_PLAYERXPRP = "显示经验值条"
	EUF_TEXT_OPTION_PLAYERXPPCT = "显示经验值百分比"
	EUF_TEXT_OPTION_PLAYERRPSHOW = "替换显示为声望值条"
	EUF_TEXT_OPTION_PLAYERTIME = "精确显示玩家Buff/Debuff时间"
	EUF_TEXT_OPTION_PETHPMP = "显示玩家宠物的HP和MP"
	EUF_TEXT_OPTION_OTWARNING = "OT 声音报警"
	EUF_TEXT_OPTION_PARTYHPMP = "显示队友的HP和MP"
	EUF_TEXT_OPTION_PARTYLEVEL = "显示队友等级"
	EUF_TEXT_OPTION_PARTYCLASS = "显示队友职业"
	EUF_TEXT_OPTION_TARGETHPPCT = "显示目标生命值百分比"
	EUF_TEXT_OPTION_TARGETTYPE = "显示目标类型或种族"
	EUF_TEXT_OPTION_TARGETCLASS = "显示目标职业"
	EUF_TEXT_OPTION_TARGETICON = "显示目标职业图标"
	EUF_TEXT_OPTION_TARGETSHIELD = "显示目标破甲值"
	EUF_TEXT_OPTION_TOTFRAME = "显示目标的目标"
	EUF_TEXT_OPTION_TOTHPPERCENT = "显示ToT的生命百分比"
	EUF_TEXT_OPTION_TOTOTFRAME = "显示目标的目标的目标"
	EUF_TEXT_OPTION_SHIFTMOVE = "Shift&鼠标左键移动ToT"

elseif ( GetLocale() == "zhTW") then
	
	EUF_TEXT_TITLE = "界面增強"
	EUF_TEXT_OPTION = "界面增強設置選項"
	EUF_TEXT_HEADER = "Enhanced Unit Frames 參數設定"
	EUF_TEXT_DEFAULT = "默認設置"
	EUF_TEXT_CONFIRM = "確定"

	EUF_TEXT_OPTION_PLAYERELITE = "玩家顯示精英頭像"
	EUF_TEXT_OPTION_TOPPANEL = "調整頭像位置適應頂部狀態條"
	EUF_TEXT_OPTION_NOEXTBORDER = "不顯示玩家頭像擴展邊框"
	EUF_TEXT_OPTION_PLAYERHPMP = "顯示玩家的HP和MP"
	EUF_TEXT_OPTION_PLAYERXPRP = "顯示經驗值條"
	EUF_TEXT_OPTION_PLAYERXPPCT = "顯示經驗值百分比"
	EUF_TEXT_OPTION_PLAYERRPSHOW = "替換顯示為聲望值條"
	EUF_TEXT_OPTION_PLAYERTIME = "精確顯示玩家Buff/Debuff時間"
	EUF_TEXT_OPTION_PETHPMP = "顯示玩家寵物的HP和MP"
	EUF_TEXT_OPTION_OTWARNING = "OT 聲音報警"
	EUF_TEXT_OPTION_PARTYHPMP = "顯示隊友的HP和MP"
	EUF_TEXT_OPTION_PARTYLEVEL = "顯示隊友等級"
	EUF_TEXT_OPTION_PARTYCLASS = "顯示隊友職業"
	EUF_TEXT_OPTION_TARGETHPPCT = "顯示目標生命值百分比"
	EUF_TEXT_OPTION_TARGETTYPE = "顯示目標類型或種族"
	EUF_TEXT_OPTION_TARGETCLASS = "顯示目標職業"
	EUF_TEXT_OPTION_TARGETICON = "顯示目標職業圖標"
	EUF_TEXT_OPTION_TARGETSHIELD = "顯示目標破甲值"
	EUF_TEXT_OPTION_TOTFRAME = "顯示目標的目標"
	EUF_TEXT_OPTION_TOTHPPERCENT = "顯示ToT的生命百分比"
	EUF_TEXT_OPTION_TOTOTFRAME = "顯示目標的目標的目標"
	EUF_TEXT_OPTION_SHIFTMOVE = "Shift&滑鼠左鍵移動ToT"

else

EUF_TEXT_TITLE = "Enhanced Unit Frames"
EUF_TEXT_OPTION = "Enhanced Unit Frames Option"
EUF_TEXT_HEADER = "Enhanced Unit Frames Setting"
EUF_TEXT_DEFAULT = "Default Setting	"
EUF_TEXT_CONFIRM = "Okay"

EUF_TEXT_OPTION_PLAYERELITE = "Show elite frame for player portrait"
EUF_TEXT_OPTION_TOPPANEL = "adjust player frame for top toolbar"
EUF_TEXT_OPTION_NOEXTBORDER = "not display player frame expand"
EUF_TEXT_OPTION_PLAYERHPMP = "show player HP&MP"
EUF_TEXT_OPTION_PLAYERXPRP = "show exp"
EUF_TEXT_OPTION_PLAYERXPPCT = "show percent of exp"
EUF_TEXT_OPTION_PLAYERRPSHOW = "replace exp to reputation"
EUF_TEXT_OPTION_PLAYERTIME = "show player Buff/Debuff time"
EUF_TEXT_OPTION_PETHPMP = "show pet's HP&MP"
EUF_TEXT_OPTION_OTWARNING = "OT sound warning"
EUF_TEXT_OPTION_PARTYHPMP = "show party HP&MP"
EUF_TEXT_OPTION_PARTYLEVEL = "show party level"
EUF_TEXT_OPTION_PARTYCLASS = "show party class"
EUF_TEXT_OPTION_TARGETHPPCT = "show percent of target's Hp"
EUF_TEXT_OPTION_TARGETTYPE = "show class of target"
EUF_TEXT_OPTION_TARGETCLASS = "show profession of target"
EUF_TEXT_OPTION_TARGETICON = "show profession icon of target"
EUF_TEXT_OPTION_TARGETSHIELD = "show expose armor of target"
EUF_TEXT_OPTION_TOTFRAME = "show target of target"
EUF_TEXT_OPTION_TOTHPPERCENT = "show Hp percent of target of target"
EUF_TEXT_OPTION_TOTOTFRAME = "show target of target of target"
EUF_TEXT_OPTION_SHIFTMOVE = "Shift&Left button to move ToT"

end