--
--	Create by iWOW (http://wow.365wave.com)
--      Modify by Alfred (http://statue.sayya.org/wowdb/)
--
	QUESTLIBRARY_NAME = "QuestLibrary";
	QUESTLIBRARY_DESC = "Quest library provides information for queries.";
	QUESTLIBRARY_TITLE = "|cffffff66"..QUESTLIBRARY_NAME.."|r";
	QUESTLIBRARY_LOADED_TEXT = QUESTLIBRARY_TITLE.." loaded";

	QUESTLIBRARY_QH_TITLE = "QuestLibrary";
	QUESTLIBRARY_QH_QUERYRESULT1 = "Search Result:";
	QUESTLIBRARY_QH_QUERYRESULT2 = "Quests";
	
	-- QUEST_MONSTERS_KILLED
	QUESTLIBRARY_QUESTOBJECT_FILTER1 = " slain";
	QUESTLIBRARY_QUESTOBJECT_FILTER2 = ":.*";
	QUESTLIBRARY_QUESTOBJECT_FILTER3 = "(Done)";

	QUESTLIBRARY_TEXT_TOOLTIP1 = " Objective [";
	QUESTLIBRARY_TEXT_TOOLTIP2 = "] Gain from ";
	QUESTLIBRARY_TEXT_TOOLTIP3 = " Located ";
	QUESTLIBRARY_TEXT_TOOLTIP4 = "Quest: ";
	QUESTLIBRARY_TEXT_TOOLTIP5 = "|cff00ffffLocation ";
	QUESTLIBRARY_TEXT_TOOLTIP6 = " have too much map notes, please delete some notes.|r";
	QUESTLIBRARY_TEXT_TOOLTIP7 = "|cFFFFFF00Quest Query (Quest Item Gains)|r\n|cFF00FF00";
	QUESTLIBRARY_TEXT_TOOLTIP8 = "|cFFFFFF00Quest Query (Accept Location)|r\n";
	QUESTLIBRARY_TEXT_TOOLTIP9 = "|cFFFFFF00Quest Query (Complete Location)|r\n";

	QUESTLIBRARY_TEXT_ACCEPTQUEST = "Accept Quest";
	QUESTLIBRARY_TEXT_COMPLETEQUEST = "Complete Quest";
	QUESTLIBRARY_TEXT_ACCEPTQUESTLOCATION = "Accept Location";
	QUESTLIBRARY_TEXT_COMPLETEQUESTLOCATION = "Complete Location";

	QUESTLIBRARY_TEXT_DELETEBUTTON = "Delete Queried Notes";
	QUESTLIBRARY_TEXT_BACKBUTTON = "Back";
	QUESTLIBRARY_TEXT_RELATEDBUTTON = "Related Location";
	QUESTLIBRARY_TEXT_QUERYBUTTON = "Quest Query";
	QUESTLIBRARY_TEXT_QUERYBUTTON_TOOLTIP =  "Query the quest NPC and related location.";
	QUESTLIBRARY_TEXT_SEARCHBUTTON = "Search Quest";
	QUESTLIBRARY_TEXT_SEARCHBUTTON_TOOLTIP = "Enter an object for quest searching.\ni.e.\"Wailing Caverns\", all the information about Wailing Caverns will be displayed.";
	QUESTLIBRARY_TEXT_REDUCED = "%d quests and %d positions reduced for your level."
	MAPNOTE_CREATEDBY = "Creator:";

	QUESTLIBRARY_GETZONE = {
		["Durotar"] = "Durotar",
		["Mulgore"] = "Mulgore",
		["The Barrens"] = "Barrens",
		["Alterac Mountains"] = "Alterac",
		["Arathi Highlands"] = "Arathi",
		["Badlands"] = "Badlands",
		["Blasted Lands"] = "BlastedLands",
		["Tirisfal Glades"] = "Tirisfal",
		["Silverpine Forest"] = "Silverpine",
		["Western Plaguelands"] = "WesternPlaguelands",
		["Eastern Plaguelands"] = "EasternPlaguelands",
		["Hillsbrad Foothills"] = "Hilsbrad",
		["The Hinterlands"] = "Hinterlands",
		["Dun Morogh"] = "DunMorogh",
		["Searing Gorge"] = "SearingGorge",
		["Burning Steppes"] = "BurningSteppes",
		["Elwynn Forest"] = "Elwynn",
		["Deadwind Pass"] = "DeadwindPass",
		["Duskwood"] = "Duskwood",
		["Loch Modan"] = "LochModan",
		["Redridge Mountains"] = "Redridge",
		["Stranglethorn Vale"] = "Stranglethorn",
		["Swamp of Sorrows"] = "SwampOfSorrows",
		["Westfall"] = "Westfall",
		["Wetlands"] = "Wetlands",
		["Teldrassil"] = "Teldrassil",
		["Darkshore"] = "Darkshore",
		["Ashenvale"] = "Ashenvale",
		["Thousand Needles"] = "ThousandNeedles",
		["Stonetalon Mountains"] = "StonetalonMountains",
		["Desolace"] = "Desolace",
		["Feralas"] = "Feralas",
		["Dustwallow Marsh"] = "Dustwallow",
		["Tanaris"] = "Tanaris",
		["Azshara"] = "Aszhara",
		["Felwood"] = "Felwood",
		["Un'Goro Crater"] = "UngoroCrater",
		["Moonglade"] = "Moonglade",
		["Silithus"] = "Silithus",
		["Winterspring"] = "Winterspring",
		["Stormwind City"] = "Stormwind",
		["Orgrimmar"] = "Ogrimmar",
		["Ironforge"] = "Ironforge",
		["Thunder Bluff"] = "ThunderBluff",
		["Darnassus"] = "Darnassis",
		["Undercity"] = "Undercity",
		["Alterac Valley"] = "AlteracValley",
		["Warsong Gulch"] = "WarsongGulch",
		["Arathi Basin"] = "ArathiBasin",
		["Eversong Woods"] = "EversongWoods",
		["Ghostlands"] = "Ghostlands",
		["Azuremyst Isle"] = "AzuremystIsle",
		["Hellfire Peninsula"] = "Hellfire",
		["Zangarmarsh"] = "Zangarmarsh",
		["The Exodar"] = "TheExodar",
		["Shadowmoon Valley"] = "ShadowmoonValley",
		["Blade's Edge Mountains"] = "BladesEdgeMountains",
		["Bloodmyst Isle"] = "BloodmystIsle",
		["Nagrand"] = "Nagrand",
		["Terokkar Forest"] = "TerokkarForest",
		["Netherstorm"] = "Netherstorm",
		["Silvermoon City"] = "SilvermoonCity",
		["Shattrath City"] = "ShattrathCity",
		["Eye of the Storm"] = "NetherstormArena",
		["Borean Tundra"] = "BoreanTundra",
		["Dragonblight"] = "Dragonblight",
		["Grizzly Hills"] = "GrizzlyHills",
		["Howling Fjord"] = "HowlingFjord",
		["Icecrown"] = "IcecrownGlacier",
		["Sholazar Basin"] = "SholazarBasin",
		["The Storm Peaks"] = "TheStormPeaks",
		["Zul'Drak"] = "ZulDrak",
		["Isle of Quel'Danas"] = "Sunwell",
		["Wintergrasp"] = "LakeWintergrasp",
		["Plaguelands: The Scarlet Enclave"] = "ScarletEnclave",
		["Dalaran"] = "Dalaran",
		["Crystalsong Forest"] = "CrystalsongForest",
		["Strand of the Ancients"] = "StrandoftheAncients",
	}

if (GetLocale() == "zhCN") then
	QUESTLIBRARY_QH_TITLE = "任务库查询";
	QUESTLIBRARY_QH_QUERYRESULT1 = "查询结果:";
	QUESTLIBRARY_QH_QUERYRESULT2 = "个任务";

	QUESTLIBRARY_QUESTOBJECT_FILTER1 = "已杀死";
	QUESTLIBRARY_QUESTOBJECT_FILTER2 = "：.*";
	QUESTLIBRARY_QUESTOBJECT_FILTER3 = "（完成）";
	
	QUESTLIBRARY_TEXT_TOOLTIP1 = "]任务目标[";
	QUESTLIBRARY_TEXT_TOOLTIP2 = "]获得: ";
	QUESTLIBRARY_TEXT_TOOLTIP3 = " 位于 ";
	QUESTLIBRARY_TEXT_TOOLTIP4 = "任务: ";
	QUESTLIBRARY_TEXT_TOOLTIP5 = "|cff00ffff区域 ";
	QUESTLIBRARY_TEXT_TOOLTIP6 = " 中的地图标记过多，请删除部分。|r";
	QUESTLIBRARY_TEXT_TOOLTIP7 = "|cFFFFFF00任务查询(任务物品获得)|r\n|cFF00FF00";
	QUESTLIBRARY_TEXT_TOOLTIP8 = "|cFFFFFF00任务查询(接受任务地点)|r\n";
	QUESTLIBRARY_TEXT_TOOLTIP9 = "|cFFFFFF00任务查询(完成任务地点)|r\n";

	QUESTLIBRARY_TEXT_ACCEPTQUEST = "接受任务";
	QUESTLIBRARY_TEXT_COMPLETEQUEST = "完成任务";
	QUESTLIBRARY_TEXT_ACCEPTQUESTLOCATION = "接受任务地点";
	QUESTLIBRARY_TEXT_COMPLETEQUESTLOCATION = "完成任务地点";

	QUESTLIBRARY_TEXT_DELETEBUTTON = "删除查询标记";
	QUESTLIBRARY_TEXT_BACKBUTTON = "返回任务说明";
	QUESTLIBRARY_TEXT_QUERYBUTTON = "地点查询";
	QUESTLIBRARY_TEXT_SEARCHBUTTON = "任务搜索";
	QUESTLIBRARY_TEXT_SEARCHBUTTON_TOOLTIP = "根据你输入的条件查找任务。\n例如输入\"哀嚎洞穴\"，就可以\n查找到所有哀嚎洞穴相关的任务。";
	MAPNOTE_CREATEDBY = "创建者：";

	QUESTLIBRARY_GETZONE = {
		["杜隆塔尔"] = "Durotar",
		["莫高雷"] = "Mulgore",
		["贫瘠之地"] = "Barrens",
		["奥特兰克山脉"] = "Alterac",
		["阿拉希高地"] = "Arathi",
		["荒芜之地"] = "Badlands",
		["诅咒之地"] = "BlastedLands",
		["提瑞斯法林地"] = "Tirisfal",
		["银松森林"] = "Silverpine",
		["西瘟疫之地"] = "WesternPlaguelands",
		["东瘟疫之地"] = "EasternPlaguelands",
		["希尔斯布莱德丘陵"] = "Hilsbrad",
		["辛特兰"] = "Hinterlands",
		["丹莫罗"] = "DunMorogh",
		["灼热峡谷"] = "SearingGorge",
		["燃烧平原"] = "BurningSteppes",
		["艾尔文森林"] = "Elwynn",
		["逆风小径"] = "DeadwindPass",
		["暮色森林"] = "Duskwood",
		["洛克莫丹"] = "LochModan",
		["赤脊山"] = "Redridge",
		["荆棘谷"] = "Stranglethorn",
		["悲伤沼泽"] = "SwampOfSorrows",
		["西部荒野"] = "Westfall",
		["湿地"] = "Wetlands",
		["泰达希尔"] = "Teldrassil",
		["黑海岸"] = "Darkshore",
		["灰谷"] = "Ashenvale",
		["千针石林"] = "ThousandNeedles",
		["石爪山脉"] = "StonetalonMountains",
		["凄凉之地"] = "Desolace",
		["菲拉斯"] = "Feralas",
		["尘泥沼泽"] = "Dustwallow",
		["塔纳利斯"] = "Tanaris",
		["艾萨拉"] = "Aszhara",
		["费伍德森林"] = "Felwood",
		["安戈洛环形山"] = "UngoroCrater",
		["月光林地"] = "Moonglade",
		["希利苏斯"] = "Silithus",
		["冬泉谷"] = "Winterspring",
		["暴风城"] = "Stormwind",
		["奥格瑞玛"] = "Ogrimmar",
		["铁炉堡"] = "Ironforge",
		["雷霆崖"] = "ThunderBluff",
		["达纳苏斯"] = "Darnassis",
		["幽暗城"] = "Undercity",
		["奥特兰克山谷"] = "AlteracValley",
		["战歌峡谷"] = "WarsongGulch",
		["阿拉希盆地"] = "ArathiBasin",
		["永歌森林"] = "EversongWoods",
		["幽魂之地"] = "Ghostlands",
		["秘蓝岛"] = "AzuremystIsle",
		["地狱火半岛"] = "Hellfire",
		["赞加沼泽"] = "Zangarmarsh",
		["埃索达"] = "TheExodar",
		["影月谷"] = "ShadowmoonValley",
		["刀锋山"] = "BladesEdgeMountains",
		["秘血岛"] = "BloodmystIsle",
		["纳格兰"] = "Nagrand",
		["泰罗卡森林"] = "TerokkarForest",
		["虚空风暴"] = "Netherstorm",
		["银月城"] = "SilvermoonCity",
		["沙塔斯城"] = "ShattrathCity",
		["风暴之眼"] = "NetherstormArena",
		["北风苔原"] = "BoreanTundra",
		["龙骨荒野"] = "Dragonblight",
		["灰熊丘陵"] = "GrizzlyHills",
		["嚎风峡湾"] = "HowlingFjord",
		["冰冠冰川"] = "IcecrownGlacier",
		["索拉查盆地"] = "SholazarBasin",
		["风暴峭壁"] = "TheStormPeaks",
		["祖达克"] = "ZulDrak",
		["奎尔丹纳斯岛"] = "Sunwell",
		["冬拥湖"] = "LakeWintergrasp",
		["东瘟疫之地：血色领地"] = "ScarletEnclave",
		["达拉然"] = "Dalaran",
		["晶歌森林"] = "CrystalsongForest",
		["远古海滩"] = "StrandoftheAncients",
	}
elseif (GetLocale() == "zhTW") then

	QUESTLIBRARY_QH_TITLE = "任務庫查詢";
	QUESTLIBRARY_QH_QUERYRESULT1 = "查詢結果:";
	QUESTLIBRARY_QH_QUERYRESULT2 = "個任務";

	QUESTLIBRARY_QUESTOBJECT_FILTER1 = "已殺死";
	QUESTLIBRARY_QUESTOBJECT_FILTER2 = ":.*";
	QUESTLIBRARY_QUESTOBJECT_FILTER3 = "（完成）";
	
	QUESTLIBRARY_TEXT_TOOLTIP1 = "]任務目標[";
	QUESTLIBRARY_TEXT_TOOLTIP2 = "]獲得: ";
	QUESTLIBRARY_TEXT_TOOLTIP3 = " 位於 ";
	QUESTLIBRARY_TEXT_TOOLTIP4 = "任務: ";
	QUESTLIBRARY_TEXT_TOOLTIP5 = "|cff00ffff區域 ";
	QUESTLIBRARY_TEXT_TOOLTIP6 = " 中的地圖標記過多，請刪除部分。|r";
	QUESTLIBRARY_TEXT_TOOLTIP7 = "|cFFFFFF00任務查詢(任務物品獲得)|r\n|cFF00FF00";
	QUESTLIBRARY_TEXT_TOOLTIP8 = "|cFFFFFF00任務查詢(接受任務地點)|r\n";
	QUESTLIBRARY_TEXT_TOOLTIP9 = "|cFFFFFF00任務查詢(完成任務地點)|r\n";

	QUESTLIBRARY_TEXT_ACCEPTQUEST = "接受任務";
	QUESTLIBRARY_TEXT_COMPLETEQUEST = "完成任務";
	QUESTLIBRARY_TEXT_ACCEPTQUESTLOCATION = "接受任務地點";
	QUESTLIBRARY_TEXT_COMPLETEQUESTLOCATION = "完成任務地點";

	QUESTLIBRARY_TEXT_DELETEBUTTON = "刪除查詢標記";
	QUESTLIBRARY_TEXT_BACKBUTTON = "返回任務說明";
	QUESTLIBRARY_TEXT_QUERYBUTTON = "地點查詢";
	QUESTLIBRARY_TEXT_SEARCHBUTTON = "任務搜索";
	QUESTLIBRARY_TEXT_SEARCHBUTTON_TOOLTIP = "根據你輸入的條件查找任務。\n例如輸入\"哀嚎洞穴\"，就可以\n查找到所有哀嚎洞穴相關的任務。";
	MAPNOTE_CREATEDBY = "創建者：";
	
	QUESTLIBRARY_GETZONE = {
		["杜洛塔"] = "Durotar",
		["莫高雷"] = "Mulgore",
		["貧瘠之地"] = "Barrens",
		["奧特蘭克山脈"] = "Alterac",
		["阿拉希高地"] = "Arathi",
		["荒蕪之地"] = "Badlands",
		["詛咒之地"] = "BlastedLands",
		["提里斯法林地"] = "Tirisfal",
		["銀松森林"] = "Silverpine",
		["西瘟疫之地"] = "WesternPlaguelands",
		["東瘟疫之地"] = "EasternPlaguelands",
		["希爾斯布萊德丘陵"] = "Hilsbrad",
		["辛特蘭"] = "Hinterlands",
		["丹莫洛"] = "DunMorogh",
		["灼熱峽谷"] = "SearingGorge",
		["燃燒平原"] = "BurningSteppes",
		["艾爾文森林"] = "Elwynn",
		["逆風小徑"] = "DeadwindPass",
		["暮色森林"] = "Duskwood",
		["洛克莫丹"] = "LochModan",
		["赤脊山"] = "Redridge",
		["荊棘谷"] = "Stranglethorn",
		["悲傷沼澤"] = "SwampOfSorrows",
		["西部荒野"] = "Westfall",
		["濕地"] = "Wetlands",
		["泰達希爾"] = "Teldrassil",
		["黑海岸"] = "Darkshore",
		["梣谷"] = "Ashenvale",
		["千針石林"] = "ThousandNeedles",
		["石爪山脈"] = "StonetalonMountains",
		["淒涼之地"] = "Desolace",
		["菲拉斯"] = "Feralas",
		["塵泥沼澤"] = "Dustwallow",
		["塔納利斯"] = "Tanaris",
		["艾薩拉"] = "Aszhara",
		["費伍德森林"] = "Felwood",
		["安戈洛環形山"] = "UngoroCrater",
		["月光林地"] = "Moonglade",
		["希利蘇斯"] = "Silithus",
		["冬泉谷"] = "Winterspring",
		["暴風城"] = "Stormwind",
		["奧格瑪"] = "Ogrimmar",
		["鐵爐堡"] = "Ironforge",
		["雷霆崖"] = "ThunderBluff",
		["達納蘇斯"] = "Darnassis",
		["幽暗城"] = "Undercity",
		["奧特蘭克山谷"] = "AlteracValley",
		["戰歌峽谷"] = "WarsongGulch",
		["阿拉希盆地"] = "ArathiBasin",
		["永歌森林"] = "EversongWoods",
		["鬼魂之地"] = "Ghostlands",
		["藍謎島"] = "AzuremystIsle",
		["地獄火半島"] = "Hellfire",
		["贊格沼澤"] = "Zangarmarsh",
		["艾克索達"] = "TheExodar",
		["影月谷"] = "ShadowmoonValley",
		["劍刃山脈"] = "BladesEdgeMountains",
		["血謎島"] = "BloodmystIsle",
		["納葛蘭"] = "Nagrand",
		["泰洛卡森林"] = "TerokkarForest",
		["虛空風暴"] = "Netherstorm",
		["銀月城"] = "SilvermoonCity",
		["撒塔斯城"] = "ShattrathCity",
		["暴風之眼"] = "NetherstormArena",
		["北風凍原"] = "BoreanTundra",
		["龍骨荒野"] = "Dragonblight",
		["灰白之丘"] = "GrizzlyHills",
		["凜風峽灣"] = "HowlingFjord",
		["寒冰皇冠"] = "IcecrownGlacier",
		["休拉薩盆地"] = "SholazarBasin",
		["風暴群山"] = "TheStormPeaks",
		["祖爾德拉克"] = "ZulDrak",
		["奎爾達納斯之島"] = "Sunwell",
		["冬握湖"] = "LakeWintergrasp",
		["東瘟疫之地: 血色領區"] = "ScarletEnclave",
		["達拉然"] = "Dalaran",
		["水晶之歌森林"] = "CrystalsongForest",
		["遠祖灘頭"] = "StrandoftheAncients",
	}
end
